- hosts: all
  vars_files:
    - defaults/main.yml
  tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Enable Oracle repos
      block:
        - yum_repository:
            name: ol7_developer_EPEL
            description: Oracle Linux $releasever Development Packages ($basearch)
            file: public-yum-ol7
            baseurl: https://yum$ociregion.oracle.com/repo/OracleLinux/OL7/developer_EPEL/$basearch/
            gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
            gpgcheck: yes
            enabled: yes

        - yum_repository:
            name: ol7_optional_latest
            description: Oracle Linux $releasever Optional Latest ($basearch)
            file: public-yum-ol7
            baseurl: https://yum$ociregion.oracle.com/repo/OracleLinux/OL7/optional/latest/$basearch/
            gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
            gpgcheck: yes
            enabled: yes

        - yum_repository:
            name: ol7_addons
            description: Oracle Linux $releasever Add ons ($basearch)
            file: public-yum-ol7
            baseurl: https://yum$ociregion.oracle.com/repo/OracleLinux/OL7/addons/$basearch/
            gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
            gpgcheck: yes
            enabled: yes
      when: ansible_distribution == 'OracleLinux'      

    - name: install additional packages
      yum:
        name:
          - ncdu
          - mc
          - htop
          - atop
          - tmux
          - screen
          - sysstat
          - iotop
          - lsof
          - tcpdump
          - nmap
          - nano
          - vim
          - telnet
          - strace
          - ltrace
          - gdisk
          - traceroute
          - lsscsi
          - pciutils
          - net-tools
          - sysfsutils
          - elinks
          - kexec-tools
          - redhat-lsb-core
          - bind-utils
          - sos
          - lynis
          - policycoreutils-python
          - smem
          - libselinux-python
          - setools-console
          - blktrace
          - bash-completion
          - yum-plugin-remove-with-leaves
          - wget

    - name: tune bashrc
      blockinfile:
        path: /root/.bashrc
        block: |
          export HISTTIMEFORMAT="%d/%m/%y %T "
          export HISTFILESIZE=10000

    - name: add color ip output to global alias
      copy:
        dest: "/etc/profile.d/colorip.sh"
        content: |
          alias ip='ip --color'
          alias ipb='ip --color --brief'

    - name: change ll alias
      replace:
        path: /etc/profile.d/colorls.sh
        regexp: 'ls -l'
        replace: 'ls -al'

    - name: generate sshd config
      template:
        src: "sshd_config.j2"
        dest: "/etc/ssh/sshd_config"
        owner: "root"
        group: "root"
        mode: "0644"
      notify:
        - test sshd config
        - restart sshd

#    - name: clear tmp directory
#      file:
#        state: "{{ item }}"
#        path: "/tmp/"
#      with_items:
#        - absent
#        - directory

  handlers:
    - name: test sshd config
      command: sshd -t

    - name: restart sshd
      service:
        name: sshd
        state: restarted
